# Generated by Django 2.1.4 on 2018-12-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='What',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=255)),
                ('etc', models.TextField()),
                ('do', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskphrase.What')),
            ],
        ),
        migrations.CreateModel(
            name='Who',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('do_does', models.CharField(default='do', max_length=16)),
                ('email', models.CharField(max_length=128)),
                ('tel', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='what',
            name='who',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskphrase.Who'),
        ),
        migrations.AddField(
            model_name='what',
            name='whom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whom', to='taskphrase.Who'),
        ),
    ]
