# Generated by Django 2.1.4 on 2018-12-07 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskphrase', '0004_what_django_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='who',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='who',
            name='django_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='who',
            name='email',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='who',
            name='tel',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
