# Generated by Django 2.1.4 on 2018-12-07 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskphrase', '0005_auto_20181207_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='who',
            name='django_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='who',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='who',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='who',
            name='tel',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
