# Generated by Django 2.1.4 on 2018-12-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskphrase', '0008_auto_20181207_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='who',
            name='do_does',
            field=models.CharField(choices=[('do', 'do'), ('does', 'does')], default='do', max_length=16),
        ),
    ]
