# Generated by Django 2.1.4 on 2018-12-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskphrase', '0010_auto_20181207_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='what',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='what',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='who',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='who',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
