# Generated by Django 2.1.4 on 2018-12-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskphrase', '0011_auto_20181207_0536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='what',
            old_name='django_user_owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='who',
            old_name='django_user_owner',
            new_name='created_by',
        ),
    ]
