# Generated by Django 2.1.4 on 2018-12-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskphrase', '0012_auto_20181207_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='what',
            name='public',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
