# Generated by Django 2.1.4 on 2018-12-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskphrase', '0013_what_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='what',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
