# Generated by Django 2.1.4 on 2019-01-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskphrase', '0014_auto_20181207_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='what',
            name='order',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
